replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.901-g4c2fff
  pullPolicy: Always
  sha: sha256:27b16c5a84a1938f8103f84ce963cd7f7c3c510a3762b5bce89dccadcc042183
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
