replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.888-g7f2de4
  pullPolicy: Always
  sha: sha256:9a5bd840cce941c4ecf0f495fba65a7a1312efb2cbe78b36915d04749b272714
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
