replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.873-gf5e765
  pullPolicy: Always
  sha: sha256:29d36e4d12ddd611857289871227f05e115695505a1c3689dbf7b87f3716d5bf
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
