replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.904-geab777
  pullPolicy: Always
  sha: sha256:f27de88dcba1d95d57d950f7b6fecb68c3bb3f36ced913763aabbef43ed4fafe
internal_nginx: 'OFF'
